<div id="tabs_main"> 
    <div class="submenu">
        <a class="heading_tab advanced_link active tab1" href="#">Generale</a>
        <a class="heading_tab advanced_link tab3" href="#">Impegni</a>
    </div>
    
    <div class="tab_contents">
        <div class="tab_content" id="general">
            Generale
        </div>
              
        <div class="tab_content" id="general">
            Impegni
        </div>
    </div>
</div>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabPane.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabs.js')); ?>