<div id="tabs_main"> 
    <div class="submenu">
        <a class="heading_tab advanced_link active tab3" href="#">Impegni</a>
    <!--    <a class="heading_tab advanced_link tab1" href="#">Messaggi</a> -->
        <a class="heading_tab advanced_link tab1" href="#">Ultime offerte</a>
        <a class="heading_tab advanced_link tab3" href="#">Ultime commesse</a>
    </div>
    
    <div class="tab_contents">

        <div class="tab_content" id="general">
        	<h2>Impegni</h2>
            <?php $this->tasks->deploy(); ?>
        </div>
<?php /*
        <div class="tab_content" id="general">
            <h2>Messaggi</h2>
            <table class="fluid">
                <?php foreach($this->messages as $m) : ?>
                    <tr>
                        <th width="20%" class="">
                            <?php echo $m['date_sent']; ?>
                        </th>
                        <th>
                            <?php echo $m['subject']; ?>
                        </th>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?php echo $m['text']; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    */ ?>
        <div class="tab_content" id="general">
        	<h2>Ultime 5 offerte assegnate</h2>
            <?php $this->offers->deploy(); ?>
        </div>
              
        <div class="tab_content" id="general">
        	<h2>Ultime 5 commesse assegnate</h2>
            <?php $this->orders->deploy(); ?>
        </div>
        
    </div>
</div>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabPane.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabs.js')); ?>