<div id="tabs_main">
    <div class="submenu">
        <a class="heading_tab advanced_link <?php echo $this->excluded ? '' : 'active'; ?> tab1" href="<?php echo $this->baseUrl('companies/list'); ?>">Elenco Aziende</a>
        <?php /* <a class="heading_tab advanced_link <?php echo $this->excluded ? 'active' : ''; ?> tab1" href="<?php echo $this->baseUrl('companies/list/excluded/1'); ?>">Escluse</a> */ ?>
        <?php if($this->acl('companies', 'create')) : ?>
        <a class="heading_tab advanced_link important" href="<?php echo $this->baseUrl('companies/edit'); ?>">Nuova Azienda</a>
        <?php endif; ?>
     <!--   <a class="heading_tab advanced_link tab4" href="#">Ricerca Avanzata</a> -->
    </div>

    <div class="tab_contents">
        <h2>Elenco Aziende</h2>
        
        <div id="all" class="tab_content"><?php $this->dag->deploy(); ?> </div>
    </div>
</div>