<div id="footer">
 <?php /*   <a href="http://www.longoweb.it" title="Longo &amp; Longo" target="_blank">Longo&amp;Longo</a> &copy;2010 */ ?>
</div>
<!--
<div id="chat-holder" class="chat-holder inactive">
    <div id="chat-panel" class="cpanel">
        <div class="chead">
            chat <a id="chat-btn2" href="#">chiudi</a>
        </div>
        <ul class="chat-users" id="chat-users">
        </ul>
    </div>    
    <div class="clear-no-margin"></div>
    <div id="chat-opener" class="chat-opener">
        <h3><a href="#" id="chat-btn1">chat (<span id="chat-on">offline</span>)</a></h3>
    </div>
</div>
-->
         <!--
<div class="chat-holder" id="">
    <div class="chat-story">
        <div class="chat-msg-from">
            me
        </div>
        <div class="chat-msg">
            <div class="chat-msg-time">
                14:39
            </div>
            <div class="chat-msg-body">
                messaggio
            </div>
        </div>
        <div class="chat-msg">
            <div class="chat-msg-time">
                14:39
            </div>
            <div class="chat-msg-body">
                messaggio secondo
            </div>
        </div>
        <div class="chat-msg-from">
            rco
        </div>
        <div class="chat-msg">
            <div class="chat-msg-time">
                14:39
            </div>
            <div class="chat-msg-body">
                come no sldasjd lkashd kljs a a a a a a a hdjkasdh laksdj hlasdjaks dhalkjsdhas kdjhl dash dajlk
            </div>
        </div>
        <div class="chat-msg">
            <div class="chat-msg-time">
                14:39
            </div>
            <div class="chat-msg-body">
                a dodop
            </div>
        </div>
    </div>
    <div class="chat-input"></div>
    <div class="chat-opener">
        <div class="chat-close"><a href="#">X</a></div>
        <h3>rco Mario Rossi</h3>
    </div>
</div>
-->