<div id="tabs_main">
<div class="submenu">
    <ul id="actiosns-menu">
        <li><a class="heading_tab advanced_link tab1" href="<?php echo $this->baseUrl('tasks'); ?>">Elenco Impegni</a></li>
        <li> 
             <a class="heading_tab advanced_link tab4 important" href="<?php echo $this->baseUrl('tasks/edit'); ?>">Nuovo impegno</a>
        </li>
        <li> 
             <a class="heading_tab advanced_link active" href="#">Dove sono?</a>
        </li>
    </ul>
</div>

<div><?php $this->dag->deploy(); ?></div>

</div>