<div id="tabs_main">
    <div class="submenu">
        <a class="heading_tab advanced_link active tab1" href="#">Dati Commessa</a>  
        <a class="heading_tab advanced_link tab2" href="#">Pianificazione</a>
        <?php if(count($this->order->rcos) > 0 && $this->order->rcos[0]['rco'] != '') : ?>
        <a class="heading_tab advanced_link tab3" href="#">Consuntivo</a>
        <?php endif; ?>
        <a class="heading_tab advanced_link tab3" href="#">Impegni</a>
    </div>

    <!--
    <div class="submenu right">
        <ul id="actiosns-menu">
	        <li>
	 			<a class="heading_tab advanced_link tab4 important" href="#">Altre Azioni</a>
	    		<ul class="action-menu">
	    			<li><a href="<?php echo $this->baseUrl('tasks/edit/id_order/' . $this->order['order_id']); ?>">Nuovo Impegno</a></li>
	    		</ul>
	    	</li>
	    </ul>
    </div>
    -->

    <div class="tab_contents">
        <div id="all" class="tab_content">
            <?php echo $this->partial('orders/detail/main.phtml', $this); ?>
        </div>

        <div id="pianificazione_div" class="tab_content">
            <?php echo $this->partial('orders/detail/pianificazione.phtml', $this); ?>
        </div>
        <?php if(count($this->order->rcos) > 0 && $this->order->rcos[0]['rco'] != '') : ?>
        <div id="consuntivo_div" class="tab_content">
			<?php echo $this->partial('orders/detail/consuntivo.phtml', $this); ?>        	
        </div>
        <?php endif; ?>
        <div id="tasks__div" class="tab_content">

            <h2>Impegni</h2>

            <ul class="contextual-menu">
                <li>
                  <a href="<?php echo $this->baseUrl('tasks/edit/id_offer/' . $this->order->offer['offer_id']); ?>"><img src="<?php echo $this->baseUrl('img/edit.png'); ?>"/> nuovo impegno</a></li>
                </li>
            </ul>

            <div><?php echo $this->partial('tasks/list.ajax.phtml', array('tasks' => $this->tasks)); ?></div>
            <?php /*
            <h2>Impegni per l'offerta</h2>
            <ul class="contextual-menu">
                <li>
                  <a href="<?php echo $this->baseUrl('tasks/edit/id_order/' . $this->order['order_id']); ?>"><img src="<?php echo $this->baseUrl('img/edit.png'); ?>"/> nuovo impegno</a></li>
                </li>
            </ul>
			<div><?php $this->tasksList->deploy(); ?></div>
            */ ?>
        </div>
    </div>

</div>

<input type="hidden" name="sid" id="sid" value="<?php echo session_id(); ?>" />

<?php $this->textboxList(); ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/dialog/Overlay.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/common/dialog/MavDialog.js')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/dialog/mavdialog.css', true)); ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/adder.js')); ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/By0MessageForm.js')); ?>

<?php $this->upload(); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/orders/detail.js?v=4')); ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabPane.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabs.js')); ?>