<div id="cpw">
<h2>Cambia Password</h2>
<form name="cpw_form" id="cpw_form"
	action="<?php echo $this->baseUrl(); ?>/admin/users/task/spw/format/json"
	method="post"><?php echo $this->formHidden('id', $this->id); ?> <?php // TODO ?>
<?php if(!$this->logged_user->has_permission('admin')) : ?>
<dl class="fleft with-margin">
	<dt><label for="oldpw"><span class="red">*</span> Vecchia Password:</label></dt>
	<dd><?php echo $this->formText('oldpw', null, array('class' => 'input-medium required')); ?></dd>
</dl>
<?php endif; ?>
<dl class="fleft">
	<dt><label for="name"><span class="red">*</span>Nuova Password:</label></dt>
	<dd><input type="password" name="password" id="password"
		class="input-medium required" /></dd>
	<dt><label for="name"><span class="red">*</span> Conferma Password:</label></dt>
	<dd><input type="password" name="cpassword" id="cpassword"
		class="input-medium required" /></dd>
</dl>
<div class="clear"></div>
<p class="submit"><input class="button" type="submit" id="spw_button"
	value="Salva" /></p>
</form>
</div>
