<div id="tabs_main">
<div class="submenu">
    <a class="heading_tab advanced_link <?php echo $this->deleted ? '' : 'active'; ?> tab1" href="<?php echo $this->baseUrl('admin/users/task/list'); ?>">Elenco Utenti</a>
    <a class="heading_tab advanced_link <?php echo $this->deleted ? 'active' : ''; ?> tab2" href="<?php echo $this->baseUrl('admin/users/task/bin'); ?>">Cestino</a>
    <!--<a class="heading_tab advanced_link tab3" href="#">Cerca</a> -->
    <a class="heading_tab advanced_link tab4 important" href="<?php echo $this->baseUrl('admin/users/task/edit'); ?>">Crea Nuovo Utente</a>
</div>
<div>
    <?php echo $this->partial('admin/users/list.ajax.phtml', array('users' => $this->users)); ?>
</div>

</div>