<div id="tabs_main">
    <div class="submenu">
        <a class="heading_tab advanced_link tab1" href="<?php echo $this->baseUrl('admin/users/task/detail/id/' . $this->user['user_id']); ?>"><?php echo $this->user['username']; ?></a>
        <a class="heading_tab advanced_link tab1" href="#">Impegni</a>
        <a class="heading_tab advanced_link tab2" href="<?php echo $this->baseUrl('files/get/p/' . base64_encode('/utenti/' . $this->user['username'])); ?>">Documenti</a>
        <a class="heading_tab advanced_link tab4 active" href="#">Report</a>
    </div>
    <div class="submenu right">
        <?php foreach($this->user['internals'] as $item) : ?>
        <a class="heading_tab advanced_link tab4" href="#">
                <span title="<?php echo $item['full_name']; ?>">
                    <?php echo $item['abbr']; ?>
                    <?php if($item['office_name']) echo ' - ' . $item['office_name']; ?>
                </span>
        </a>
        <?php endforeach; ?>
    </div>

    <div class="tab_contents">

        <div class="tab_content" id="anagrafica-info">

            <h2>Report Utente: <?php echo $this->user['username']; ?></h2>

            <div id="tasks-search" class="search-wrapper">

                <h3>Filtri di Ricerca</h3>

                <form action="<?php echo $this->baseUrl('admin/users/task/report/id/' . $this->user['user_id']); ?>" method="post" name="dag_form_<?php echo $this->_id; ?>" id="report-search">

                    <ul class="contextual-menu">
                        <li>
                            <a class="report-export" href="#"><img src="<?php echo $this->baseUrl('/img/export.png'); ?>"> esporta</a>
                        </li>
                    </ul>

                    <input type="hidden" name="dalist" value="report" />
                    <input type="hidden" name="_export" id="_export" value="0" />


                    <input type="hidden" name="ashidden" id="ashidden" value="0" />
                    <?php echo $this->search->render(); ?>

                    <div style="clear: both;"></div>
                    <div class="search-element">
                        <div class="search-element-label">&nbsp;</div>
                        <div class="search-element-field">
                            <input type="reset" value="annulla" />
                            <input type="submit" value="cerca" />
                        </div>
                    </div>
                </form>
            </div>

            <div id="report-container">

                <?php echo $this->partial('admin/users/report.ajax.phtml', $this); ?>

            </div>

        </div>

    </div>

</div>

<?php /* ADVANCED SEARCH STUFF */ ?>

<?php $this->headScript()->prependFile($this->baseUrl('/js/common/jdatepicker/daterangepicker.jQuery.js')); ?>
<?php $this->headScript()->prependFile($this->baseUrl('/js/common/jquery.multiselect.min.js')); ?>
<?php $this->headScript()->prependFile($this->baseUrl('/js/jquery-ui-1.8.7.custom.min.js')); ?>
<?php $this->headScript()->prependFile($this->baseUrl('/js/jquery-1.4.4.js')); ?>

<?php $this->headLink()->appendStylesheet($this->baseUrl('/js/common/jdatepicker/css/ui.daterangepicker.css', true)); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/jquery/smoothness/jquery-ui-1.8.7.custom.css', true)); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/multiselect/multiselect.css', true)); ?>


<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabPane.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabs.js')); ?>

<script type="text/javascript">
    jQuery(document).ready(function() {

        jQuery('.date-range').each(function(i,e){
            jQuery(e).daterangepicker({
                dateFormat: 'dd/mm/yy',
                rangeStartTitle: 'Data Da',
                rangeEndTitle: 'Data a',
                doneButtonText: 'fatto',
                prevLinkText: 'prec',
                nextLinkText: 'succ',
                doneButtonText: 'fatto'
            });
        });
        jQuery('.multiple-select').each(function(i,e){
            jQuery(e).multiselect({
                selectedList: 3,
                checkAllText: 'tutte',
                uncheckAllText: 'nessuna',
                noneSelectedText: 'Scegli una o piu\' opzione',
                selectedText: '# selezionati'
            });
        });

        var form = document.id('report-search');

        jQuery('.report-export').click(function(ev){
            jQuery('#_export').val(1);
            form.submit();
            jQuery('#_export').val(0);
            ev.preventDefault();
        });

        form.set('send', {
            url: form.get('action') + '/format/html',
            method: 'post',
            update: 'report-container',
            useSpinner: true,
            onSuccess: function(d){
                document.id('report-container').set('html', d);
            }
        });

        document.id('report-search').addEvent('submit', function(ev){
            form.send();
            /*
            if(!r){
                r = new Request.HTML({
                    url: ev.target.get('action') + '/format/html',
                    update: 'report-container',
                    useSpinner: true
                });

            }
            r.post(ev.target);
            */
            ev.preventDefault();
        });


    });
</script>