<div id="tabs_main">
    <div class="submenu">
        <a class="heading_tab advanced_link active tab1" href="#">Dati</a>
    </div>

    <div class="tab_contents">
    
        <div id="detail" class="tab_content">
            <h2>Nota Credito: <?php echo $this->invoice->code_invoice; ?> -- <?php 
                echo ($this->invoice->status == 1) ? 'Chiusa' : 'Aperta';
            ?></h2>
            
             <ul class="contextual-menu">
                <?php if($this->invoice->status == 0) : ?>
                    <li><a id="pc" href="#"><img src="<?php echo $this->baseUrl('img/edit.png'); ?>"/> Pagato</a></li>
                <?php endif; ?>
                <li><a href="#"><img src="<?php echo $this->baseUrl('img/edit.png'); ?>"/>  Stampa</a></li>
            </ul>
            
            <?php echo $this->formHidden('invoice_id', $this->invoice->invoice_id); ?>
            
            <table class="detail fluid">
                <tr>
                    <th colspan="4">Dati Azienda</th>
                </tr>
                <tr>
                    <td class="label">Ragione Sociale:</td>
                    <td>
                        <a href="<?php echo $this->baseUrl('companies/detail/id/' 
                            . $this->invoice->company->company_id); ?>" title="dettaglio azienda">
                            <?php echo $this->invoice->company['ragione_sociale']; ?>
                        </a>
                    </td>
                    <td class="label">Partita IVA:</td>
                    <td><?php echo $this->invoice->company['partita_iva']; ?></td>
                </tr>
                <tr>
                    <td class="label">Codice Fiscale:</td>
                    <td><?php echo $this->invoice->company['cf']; ?></td>
                    <td class="label">IBAN:</td>
                    <td><?php echo $this->invoice->company['iban']; ?></td>
                </tr>
                <tr>
                    <th colspan="4">Dati Nota Credito</th>
                </tr>
                <tr>
                    <td class="label">Importo</td>
                    <td>
                        <?php echo number_format(- $this->invoice->importo, 2, ',', '.'); ?> &euro;
                    </td>
                    <td class="label">Tipologia di pagamento</th>
                    <td>
                        <?php echo $this->invoice->tipo_pagamento_name; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label">Data Nota Credito:</th>
                    <td>
                        <?php echo Maco_Utils_DbDate::fromDb($this->invoice->date_invoice); ?>
                    </td>
                    <td class="label">Scadenza:</th>
                    <td>
                        <?php echo Maco_Utils_DbDate::fromDb($this->invoice->date_end); ?>
                    </td>
                </tr>
            </table>
            
        </div>  
        
    </div>
        
        
</div>


<?php $this->headScript()->appendFile($this->baseUrl('/js/common/dialog/Overlay.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/common/dialog/MavDialog.js')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/dialog/mavdialog.css', true)); ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/By0MessageForm.js')); ?>


<?php $this->headScript()->appendFile($this->baseUrl('/js/administration/credito.js')); ?>