<div id="tabs_main">
    <div class="submenu">
        <a class="heading_tab advanced_link active tab1" href="#">Bacheca</a>
        <a class="heading_tab advanced_link tab4" href="<?php echo $this->baseUrl() . '/administration/list/'; ?>">Elenco</a>
    </div>

    <div class="tab_contents">
        <h2>Bacheca Amministrazione</h2>
        
    </div>
        
        
</div>


<?php $this->headScript()->appendFile($this->baseUrl('/js/common/dialog/Overlay.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/common/dialog/MavDialog.js')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/dialog/mavdialog.css', true)); ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/By0MessageForm.js')); ?>


<?php $this->headScript()->appendFile($this->baseUrl('/js/offers/detail.js')); ?>