<div id="tabs_main">
    <div class="submenu">
        <ul id="actiosns-menu">
            <li><a class="heading_tab advanced_link active tab1" href="#"><?php echo $this->label; ?></a></li>
        </ul>
    </div>
    <ul class="contextual-menu" style="margin-right: 160px;">
            <li>
              <a id="makeinvoice" href="#" ><img src="<?php echo $this->baseUrl('img/edit.png'); ?>"/> crea draft fattura</a>
            </li>
        </ul>
    <div>
        
        <?php $this->dag->deploy(); ?>
        <div style="text-align:right;margin-right: 80px">
            <h3>Totale: <?php echo number_format($this->total, 2, ',', '.'); ?> &euro;</h3>
        </div>
    </div>
</div>

<?php $this->headScript()->appendFile($this->baseUrl('/js/administration/moments.js?v=2')); ?>