<tr><th colspan="4">Azione Preventiva Avviata</th></tr>
<tr>
    <td class="label">RSQ</td>
    <td>
        <?php echo $this->story['creator']; ?>
    </td>
    <td class="label">Responsabile Azione Preventiva:</td>
    <td>
        <?php echo $this->story['user']; ?>
    </td>
</tr>
<tr>
    <td class="label">Informazioni Aggiuntive:</td>
    <td colspan="3">
        <?php echo nl2br($this->story['text1']); ?>
    </td>
</tr>
