<tr><th colspan="4">Trattamento Eseguito</th></tr>
<tr>
    <td class="label">Responsabile del Trattamento</td>
    <td>
        <?php echo $this->story['creator']; ?>
    </td>
    <td class="label">Data Risoluzione:</td>
    <td>
        <?php echo Maco_Utils_DbDate::fromDb($this->story['date2']); ?>
    </td>
</tr>
<tr>
    <td class="label">Risoluzione:</td>
    <td colspan="3">
        <?php echo nl2br($this->story['text1']); ?>
    </td>
</tr>
