<tr><th colspan="4">Segnalazione Rimandata</th></tr>
<tr>
    <td class="label">RSQ</td>
    <td>
        <?php echo $this->story['creator']; ?>
    </td>
    <td class="label">Data Rimando:</td>
    <td>
        <?php echo Maco_Utils_DbDate::fromDb($this->story['date1']); ?>
    </td>
</tr>
<tr>
    <td class="label">Motivazione:</td>
    <td colspan="3">
        <?php echo nl2br($this->story['text1']); ?>
    </td>
</tr>