<form name="mod_prevention_verifica_form" id="mod_prevention_verifica_form"
      action="<?php echo $this->baseUrl(); ?>/sdm/mpv/save/1/format/json"
      method="post">
    <?php echo $this->formHidden('id', $this->data['sdm_id']); ?>
    <div class="fieldset-container">
        <h4>Dati Verifica</h4>
        <dl>
            <dt><label for="descrizione">Verifica della Azione Preventiva:</label></dt>
            <dd>
                <?php echo $this->formTextarea($this->inputNamePrefix . 'verification', $this->data['verification'], array('class' => 'input-big required', 'rows' => 4)); ?>
            </dd>
        </dl>

        <div class="clear"></div>

        <p class="submit"><input class="button" type="submit" value="salva" /></p>

    </div>
</form>