<div id="tabs_main">
	<div class="submenu">
		<a class="heading_tab advanced_link active tab1" href="#">Elenco <?php echo $this->labels['plurale']; ?></a>
		<a class="heading_tab advanced_link tab4 important" href="<?php echo $this->baseUrl('admin/common/item/' . $this->item . '/task/edit'); ?>">Nuova <?php echo $this->labels['singolare']; ?></a>
	</div>
	
	<div><?php $this->dag->deploy(); ?></div>
	
</div>