<div id="tabs_main">
	<?php $labels = (array)($this->labels ?? []); ?>
	<div class="submenu">
		<a class="heading_tab advanced_link active tab1" href="#">Elenco <?php echo $labels['plurale'] ?? ''; ?></a>
		<a class="heading_tab advanced_link tab4 important" href="<?php echo $this->baseUrl('admin/common/item/' . $this->item . '/task/edit'); ?>">Nuova <?php echo $labels['singolare'] ?? ''; ?></a>
	</div>
	
	<div><?php $this->dag->deploy(); ?></div>
	
</div>
