<div id="tabs_main">
    <div class="submenu">
        <a class="heading_tab advanced_link active tab1" href="#">Offerta <?php echo $this->offer['code_offer']; ?></a>
        <a class="heading_tab advanced_link tab4" href="#">Storia Revisioni</a>
        <a class="heading_tab advanced_link tab4" href="#">Impegni</a>
    </div>
<?php /*       
    <div class="submenu right">
    	<ul id="actiosns-menu">
            <?php // HARD CODED 4 = id stato offerta aggiudicata ?>
            <?php if($this->offer['id_status'] != 4) : ?>
			    <li><a class="heading_tab advanced_link tab4" href="<?php echo $this->baseUrl('offers/edit/id/' . $this->offer['offer_id']); ?>">Modifica</a></li>
            <?php endif; ?>
	        <li> 
	 			<a class="heading_tab advanced_link tab4 important" href="#">Altre Azioni</a>
	    		<ul class="action-menu">
                    <?php if($this->offer['id_order'] != '') : ?>
                        <li><a href="<?php echo $this->baseUrl() . '/orders/detail/id/' . $this->offer['id_order']; ?>" title="vedi commessa">Vedi Commessa</a></li>
                    <?php else : ?>
                        <?php if($this->offer['id_status'] != 4) : ?>
                    	    <li><a href="#" id="cs">Cambia Stato</a></li>
                            <!--  <li><a href="<?php echo $this->baseUrl() . '/offers/makeorder/id/' . $this->offer['offer_id']; ?>" title="crea commessa">Crea Commessa</a></li> -->
                        <?php else: ?>
                            <li><a href="#" title="crea commessa" id="cco">Crea Commessa</a></li>
                        <?php endif; ?>
                    <?php endif; ?>
                    <li><a href="<?php echo $this->baseUrl('tasks/edit/id_offer/' . $this->offer['offer_id']); ?>">Nuovo Impegno</a></li>
	    			<!-- <li><a href="#">Esporta</a></li> -->
	    		</ul>
	    	</li>
	    </ul>
    </div>
*/ ?>

    <div class="tab_contents">
    
        <div id="detail" class="tab_content">
            <?php echo $this->partial('offers/detail/main.phtml', $this); ?>
        </div>
        
        <div id="story" class="tab_content">
            <?php echo $this->partial('offers/detail/revisions.phtml', array('revisions' => $this->revisions, 'offer' => $this->offer)); ?>
        </div>

        <div id="tasks-offer" class="tab_content">

			<h2>Impegni</h2>

            <ul class="contextual-menu">
                <li>
                  <a href="<?php echo $this->baseUrl('tasks/edit/id_offer/' . $this->offer['offer_id']); ?>"><img src="<?php echo $this->baseUrl('img/edit.png'); ?>"/> nuovo impegno</a></li>
                </li>
            </ul>

            <div><?php echo $this->partial('tasks/list.ajax.phtml', array('tasks' => $this->tasks)); ?></div>

            <?php /*
            <div><?php $this->tasksList->deploy(); ?></div>
            */ ?>
        </div>
    </div>
        
        
</div>

<input type="hidden" name="sid" id="sid" value="<?php echo session_id(); ?>" />

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/dialog/Overlay.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/common/dialog/MavDialog.js')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/dialog/mavdialog.css', true)); ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/By0MessageForm.js')); ?>

<?php $this->upload(); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/offers/detail.js?v5')); ?>

<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabPane.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/common/tabs.js')); ?>